### ISSUE TITLE
RSpec

### ISSUE THREAD

**Issue by fukuiretu** [sekainohajimari/ikyusan-api#42]
### TODO
- [x] group_controller.rb
- [x] idea_controller.rb
- [x] invite_controller.rb
- [x] like_controller.rb
- [x] notifications_controller.rb
- [x] profile_controller.rb
- [x] topic_controller.rb

**Comment by fukuiretu** [comment]
API単位で正常系だけでも書いておこう。。

**Comment by fukuiretu** [comment]
rspec-request_describer使う

**Comment by fukuiretu** [comment]
とりあえずgroup apiはできた。あとは同じ要領で他のapiのspecも量産していく。

**Comment by fukuiretu** [comment]
faker使ってみる

**Comment by fukuiretu** [comment]
あと3コントローラー...

**Comment by fukuiretu** [comment]
`like_controller.rb`に着手する

**Comment by fukuiretu** [comment]
next `invite_controller.rb`

**Comment by fukuiretu** [comment]
invite後のnotificationとlike後のnotificationの確認してなかった...

**Comment by fukuiretu** [comment]
done
